---
resources:
- name: gp-common-go-libs
  type: git
  source:
    uri: https://github.com/adam8157/gp-common-go-libs
    branch: master

jobs:
- name: units
  plan:
  - aggregate:
    - get: gp-common-go-libs
      trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
      inputs:
      - name: gp-common-go-libs
        path: go/src/github.com/adam8157/gp-common-go-libs
      run:
        path: bash
        args:
        - -c
        - |
          set -ex
      
          export GOPATH=$PWD/go
          export PATH=$GOPATH/bin:$PATH
      
          cd $GOPATH/src/github.com/adam8157/gp-common-go-libs
          make depend
          make test
